server:
  port: 8084
  servlet:
    context-path: '/ead-notificacao/'

spring:
  application:
    name: ead-notificacao-service
  config:
    import: 'optional:configserver:'
  cloud:
    config:
      discovery:
        serviceId: ead-config-server
  datasource:
    url:  jdbc:postgresql://localhost:5432/ead-notificacao
    username: postgres
    password: banco123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always
  rabbitmq:
    addresses: amqps://oqaevxaf:6KU7WK_x0k2Et0CwgwlOOdf95NAR4uPG@woodpecker.rmq.cloudamqp.com/oqaevxaf


logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO


# inserir broker properties
ead:
  broker:
    exchange:
      notificacaoCommandExchange: ead.notificacaocommand
    queue:
      notificacaoCommnadQueue: ## nome da fila
        name: ead.notificacaocommand.ms.notificacao
    key: # bainding
      notificaoCommandKey: ms.notificacao      
      
## config basicAuthenticatio por causa da dependencia do springSecurty no caso se o projeto tiver um confg-server Global não necessidade de colocar em cada ms 

  serviceRegistry:
    username: serviceregistry
    password: 'ead123sr'      
      
      


management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

eureka:
  client:
    serviceUrl:
##    defaultZone: 'http://localhost:8761/eureka'
      defaultZone: 'http://${ead.serviceRegistry.username}:${ead.ead.serviceRegistry.username}@localhost:8761/eureka' ## nova url por causa do spring Security
  instance:
    hostname: localhost



































## conexao com banco
## nome aplicacao
#spring.application.name=hr-worker 
#server.port=8001

#Database configuration
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.username=sa
#spring.datasource.password=

#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
